FROM node:22

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

# Install all dependencies (including dev)
RUN npm install

# Copy the rest of the code
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]