services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    labels:
      app.name: wonderstacked
      app.env: production
    restart: unless-stopped
